---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runners
  namespace: actions
spec:
  template:
    spec:
      repository: Ezekielhng200483/hng_boilerplate_nextjs
      labels:
        - my-custom-runner
      env: []